### ISSUE TITLE
AngularRampLogger giving error

### ISSUE THREAD

**Issue by AHEADa** [acmerobotics/road-runner-quickstart#352]
Hello, when we checked the results of AngularRampLogger, it gives this error:

Error: More rotation about the +y-axis than the +z-axis. Fix the IMU orientation and run again.
Error: More rotation about the +y-axis than the +z-axis. Fix the IMU orientation and run again.
at xh (http://192.168.43.1:8080/assets/common-dae3fb6c.js:3611:126139)
at id (http://192.168.43.1:8080/assets/common-dae3fb6c.js:3611:126322)
at HTMLButtonElement.<anonymous> (http://192.168.43.1:8080/assets/common-dae3fb6c.js:3611:130929)

Before commissioning, we adjusted the orientation of the IMU to our robot. We double checked it, and it seems is correct.

Here is our angular ramp log file.
[Uploading angular-ramp-1705729139785.json…]()

**Comment by AHEADa** [comment]
We have solved this issue. It's not a problem with the IMU. We set the wheel motor and encoders to wrong direction by mistake.

Suggestion: Place a label on the robot to indicate the team-agreed front face of the robot. This will avoid confusion later – really!
