### ISSUE TITLE
FTC Robot Controller app crashing.

### ISSUE THREAD

**Issue by Jones828** [acmerobotics/road-runner-quickstart#438]
### RR FTC Version

0.1.14

### Observed Behavior

When I try to run the quickstart. Having made no changes at all. The FTC Robot Controller app on the Driver Hub crashes.

In the logs It reports this when it does so.

```
2024-11-10 18:07:09.898  2468-2468  AndroidRuntime          com.qualcomm.ftcrobotcontroller      E  FATAL EXCEPTION: main
                                                                                                    Process: com.qualcomm.ftcrobotcontroller, PID: 2468
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference
                                                                                                    	at com.qualcomm.robotcore.wifi.WifiDirectAssistant$WifiDirectConnectionInfoListener.onConnectionInfoAvailable(WifiDirectAssistant.java:157)
                                                                                                    	at android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler.handleMessage(WifiP2pManager.java:979)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2024-11-10 18:07:09.997  2468-2468  Process                 com.qualcomm.ftcrobotcontroller      I  Sending signal. PID: 2468 SIG: 9
2024-11-10 18:07:10.153   413-530   InputDispatcher         system_server                        E  channel 'a7ddd14 com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
---------------------------- PROCESS ENDED (2468) for package com.qualcomm.ftcrobotcontroller ----------------------------

```

Can you please advice how we can proceed?

**Comment by rbrott** [comment]
Please report this upstream at https://github.com/FIRST-Tech-Challenge/FtcRobotController/
